# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da5e36317f582303d37bac71bca48d06a6d1028140c8edeef1d2dff71448b77911611a8953409f184378d08f5774cd02403b3b7fdb85b3e12a35578c2c5181dc

test:
  secret_key_base: 7fc4203e391d94486d29f4c1a046125bbbba28e96c5a4f59f92f03d09728340393b80ab6416f043dac09876762296c9c14805f376a1bb8f0f9085dc6c2ffc9d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
